# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  init:
    desc: Preparar el proyecto en una PC nueva
    cmds:
      - python -m venv .venv
      - python -m pip install --upgrade pip
      - python -m pip install -r requirements.txt
      - pio pkg install

  hmi:test:
    desc: Probar el HMI con eventos MQTT simulados
    cmds:
      - python test/simular_eventos_mqtt.py --host 127.0.0.1 --topic cheve --pause 1 ciclo

  hmi:run:
    desc: Ejecutar el HMI
    cmds:
      - python hmi/app.py --host 127.0.0.1 --port 8080 --mqtt-host 127.0.0.1 --mqtt-port 1883 --mqtt-topic cheve
